# Generated by Django 3.2.7 on 2021-10-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211025_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='multipleimage',
            name='images',
            field=models.FileField(upload_to='media/'),
        ),
    ]
