# Generated by Django 3.2.7 on 2021-11-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_multipleimage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
