# Generated by Django 3.2.7 on 2021-11-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_post_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleImage',
        ),
    ]
